# Generated by Django 4.2.3 on 2023-07-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='crazy_credits',
        ),
    ]
