# Generated by Django 4.2.3 on 2023-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_videogame_crazy_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castvideo',
            name='castvideo',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
