# Generated by Django 4.2.3 on 2023-07-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_cast_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='alsoknownas',
            new_name='officialsite',
        ),
    ]
